add logging and retries
zypp-io/twinfield pull request #87
Opened 2022-05-26 09:51 UTC by TimvdHeijden

2022-05-26 09:51 UTC, TimvdHeijden commented
@melvinfolkers I could not run the testsuite, not sure why.

2022-05-27 09:22 UTC, TimvdHeijden commented
> @melvinfolkers I could not run the testsuite, not sure why.

Inmiddels doen de tests het.

2022-05-27 09:24 UTC, TimvdHeijden commented
TODO: See how we can make the while/retry/try/except block a function instead of ten times the same code.

2022-06-07 21:40 UTC, erfannariman commented
@TimvdHeijden  zou je ook kunnen kijken of je delen (of alles) van #86 hierin kan meenemen?

2022-06-07 21:50 UTC, erfannariman requested changes
Couple remarks.

2022-06-07 21:50 UTC, erfannariman commented on twinfield/login.py
> +        return output
Can you add docstrings to this function. So it's easier to understand what is happening.

2022-06-07 21:50 UTC, erfannariman commented on twinfield/login.py
> +    def do_retry_request(self, url, headers, data=None, special_error=None, req_type="POST"):
Can we just name the function `do_request`. A retry is inherit to doing a request.

2022-06-07 21:50 UTC, erfannariman commented on twinfield/offices.py
> +        headers = {"Content-Type": "text/xml", "Accept-Charset": "utf-8"}
Since the headers are the same everywhere, can we move it somewhere else? Or in the __init__, or at the top of the file as `HEADERS = ...`

2022-06-08 19:59 UTC, TimvdHeijden commented
@melvinfolkers Feedback of Erfan is included in the latests commits.

2022-06-10 07:54 UTC, melvinfolkers commented on twinfield/__init__.py
> +
The logging configuration is advised not to be present in packages. read about it here: 
https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library

2022-06-10 10:58 UTC, melvinfolkers approved these changes
Gezamelijk gereviewed, geen opmerkingen meer

2022-06-10 11:03 UTC, merged